FROM ubuntu:18.04

MAINTAINER Shaun Freeman <shaun@shaunfreeman.co.uk>

COPY fpm-pool.conf /tmp/fpm-pool.conf
COPY compile-php.sh /usr/local/bin/compile-php.sh
RUN ["chmod", "+x", "/usr/local/bin/compile-php.sh"]

RUN apt-get update \
    && apt-get install -y --no-install-recommends  \
        wget \
        file \
        ca-certificates \
        build-essential \
        autoconf \
        bison \
        cmake \
        pkg-config \
        re2c \
        git \
        dpkg-dev \
        libprotobuf-dev \
        libboost-dev \
        libcurl4-openssl-dev \
        libfreetype6-dev \
        libjpeg-turbo8-dev \
        libpng-dev \
        libicu-dev \
        libmysqlclient-dev \
        libssl-dev \
        zlib1g-dev \
        libxml2-dev \
        curl \
        libprotobuf10 \
        protobuf-compiler \
        libfreetype6 \
        zlib1g \
        libjpeg-turbo8 \
        libxml2 \
    && compile-php.sh \
    # clean up
    && apt-get remove -y --no-install-recommends  \
        wget \
        file \
        build-essential \
        autoconf \
        bison \
        cmake \
        pkg-config \
        re2c \
        git \
        dpkg-dev \
        libprotobuf-dev \
        libboost-dev \
        libcurl4-openssl-dev \
        libfreetype6-dev \
        libjpeg-turbo8-dev \
        libpng-dev \
        libicu-dev \
        libmysqlclient-dev \
        libssl-dev \
        zlib1g-dev \
        libxml2-dev \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

COPY docker-php-entrypoint.sh /usr/local/bin/
RUN ["chmod", "+x", "/usr/local/bin/docker-php-entrypoint.sh"]
ENTRYPOINT ["/usr/local/bin/docker-php-entrypoint.sh"]

STOPSIGNAL SIGQUIT

EXPOSE 9000
CMD ["php-fpm"]

#ARG user
#ARG uid

#RUN useradd -u $uid $user \
    #&& echo "user = $user" >> /usr/local/etc/php-fpm.d/zz-docker.conf \
   # && echo "group = $user" >> /usr/local/etc/php-fpm.d/zz-docker.conf \
   # && chown -R $user:$user /var/www
